# Site settings
title:       Hekima Development Blog
email:       contact@hekima.com
author:      Hekima Developers
description: ""
baseurl:     ""
#url:         "http://hekima.github.io"
url:         "http://developers.hekima.com"
comments: true

# Google analytics
google_analytics: UA-57052292-1

# Optional features
animated:           true
show_related_posts: true
show_post_footers:  false

# Social icons
show_social_icons: false
github_username: hekima
twitter_username: hekima
google_plus_id: 
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
#markdown:     kramdown
permalink:    pretty
#pygments: true
markdown: redcarpet
redcarpet:
  extensions: ["smart", "no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
paginate:     3
sass:
  compressed: true

# Disqus
disqus:
    shortname: 'hekimadev'

gems :
    - jekyll-paginate

